### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by wh4leF1ND3R** [youyuge34/PI-REC#1]
rt,utf8不支持,gui打不开
俺寻思打开里面中文也是乱码

**Comment by youyuge34** [comment]
Plz attach the full error log and I strongly recommend u to type in English~ 😆             
All the files are encoded with `utf-8` format.

**Comment by wh4leF1ND3R** [comment]
> Plz附上完整的错误日志，我强烈建议你输入英文〜 😆
> 所有文件都以`utf-8`格式编码。

什么,竟然是utf8,问题关闭
我是傻子
