### ISSUE TITLE
Scripts for training

### ISSUE THREAD

**Issue by mabdullahrafique** [youyuge34/PI-REC#15]
Hello!
Can you push the training script to github or email me (mrafique.bese17seecs@seecs.edu.pk).
It would be very great.

**Comment by burning846** [comment]
> Hello!
> Can you push the training script to github or email me ([mrafique.bese17seecs@seecs.edu.pk](mailto:mrafique.bese17seecs@seecs.edu.pk)).
> It would be very great.

If you get the code, could you share it with me (sbn1998@pku.edu.cn)?

**Comment by mabdullahrafique** [comment]
No, I did not got the code.

**Comment by July-chat** [comment]
I want to get the training script too, If you get the code, could you share it with me(wpserendipity@163.com)? thank you

**Comment by abi98213** [comment]
No - I did not get the training script.
