### ISSUE TITLE
模式2下选择完两张图片以后报错

### ISSUE THREAD

**Issue by LYQhh** [youyuge34/PI-REC#4]
![报错信息](https://user-images.githubusercontent.com/48676289/55178840-27d02080-51c1-11e9-9a2c-0e64d786405b.png)
报错信息如图所示，其中第一行是变量edge_file的值。（我在第一次报错后经查阅资料在tool_draw.py添加了debug代码，见下图。排除了路径中的反斜线转义问题）
![image](https://user-images.githubusercontent.com/48676289/55179008-90b79880-51c1-11e9-9a04-5432827aa843.png)

**Comment by youyuge34** [comment]
I guess you meet the problem the same as #5   
Make sure your path is English without Chinese characters.

**Comment by LYQhh** [comment]
嗯，确实是路径名中出现了中文的问题，谢谢！
