### ISSUE TITLE
cv.imread不支持中文路径

### ISSUE THREAD

**Issue by fk1995** [youyuge34/PI-REC#5]
改成英文路径以后能正确读取 中文文件夹名读取出来是None但是不报错 之后resize时报错

**Comment by youyuge34** [comment]
It is the problem of `OpenCV` instead of PI-REC, who only accepts `non-ascii` path.       
You can add the following line by yourself, which could probably cause other bugs. I believe it is always a good habit to keep the file path containing ASCII words only. 
```
cv2.imdecode(np.fromfile(path_file,dtype=np.uint8),-1)
```
