### ISSUE TITLE
窗口大小可以自己设置吗？

### ISSUE THREAD

**Issue by zhangdanfeng888** [youyuge34/PI-REC#6]
请问最后的结果窗口大小是128*128的吗？能不能放大呢？是因为训练数据集的图片大小是128*128的原因，所以窗口大小只能是128*128吗？

**Comment by youyuge34** [comment]
A lot of reasons:
- The training dataset of anime is 128x128. Larger image size for testing is meaningless.
- If you use larger window size (e.g. 256x256) and add `cv.resize()` function when preprocessing the input, the input edge after `resize` algorithm  will be totally different to your hand drawn edge in window of 128x128. 
- Future work: I am not sure that if our model could handle with training large image like 512x512, which may need multi-scale architecture optimization like in GauGAN.

**Comment by zhangdanfeng888** [comment]
好的，谢谢大佬！再问一个问题，训练模型的代码什么时候能推送到github上呢？

**Comment by youyuge34** [comment]
> 好的，谢谢大佬！再问一个问题，训练模型的代码什么时候能推送到github上呢？

@youning0701 Training phase is truly comprehensive, and I am thinking about opening a new project for training just like ESR-GAN they did. In short, we have no time on it during this month.

**Comment by zhangdanfeng888** [comment]
Okay, thanks a lot~
