### ISSUE TITLE
Drawing but not result

### ISSUE THREAD

**Issue by jinfagang** [youyuge34/PI-REC#7]
Load edge but no result show:

![image](https://user-images.githubusercontent.com/21303438/55228410-f86af380-5254-11e9-8ab2-51e1f8ca1344.png)

**Comment by youyuge34** [comment]
Your edge and color domain shown in `OpenCV` windows are fairly strange. They should be shown as the same as the ones you choose in `/example`.        

The output window is dark by default, you should press the keyboard `g` for the output
 manually. Plz read the newest user manual about keyboard press~
